package geekcode.takatuf.Enums;

public enum TrackingInfo {
    PROCESSING,
    SHIPPED,
    DELIVERED,
    ACCEPTED_BY_STORE,
    REJECTED_BY_STORE,
    COUNTER_OFFER_BY_STORE,
    COUNTER_OFFER_BY_BUYER,
    REJECTED_BY_BUYER,
    CANCELLED_BY_USER,
    ACCEPTED_BY_BUYER,
    CANCELLED_BY_STORE,
    PENDING
}
