spring.application.name=Source-Safe
server.port=8080

# Enable Tomcat access logs
server.tomcat.accesslog.enabled=true

# JPA and Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/takatuf_db?createDatabaseIfNotExist=true
spring.datasource.username=test
spring.datasource.password=test

# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khajbdran@gmail.com
spring.mail.password=gorvrxjkdwxgyoxf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.transport.protocol=smtp
spring.mail.debug=true

# JWT
jwt.secret=MjgwNGRkMDYzMGQ1MzAyZjAwMzYyYjE1MzgzNTc3ZDNhMmExMmFkZTYwZDgxYmFiYzZkZGJmMzZkNjZmZDA2Zg==
jwt.expiration-time=86400000
<<<<<<< HEAD
app.frontend.url=${APP_FRONTEND_URL}
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
spring.mail.properties.mail.smtp.starttls.required=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED}
spring.mail.transport.protocol=${SPRING_MAIL_TRANSPORT_PROTOCOL}
spring.mail.debug=${SPRING_MAIL_DEBUG}
logging.level.org.springframework.web=DEBUG
logging.level.geekcode.takatuf=DEBUG
=======

# File upload settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
gemini.api.key= AIzaSyDdixCPR0OHxggnIAFAcYtdLs_6ZIAcxaE

>>>>>>> a9527f8b6e7f44ae562696c28921a61d981bdead
