apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: takatuf
type: Opaque
stringData:
  spring.datasource.url: jdbc:postgresql://postgres:5432/takatuf
  spring.datasource.username: test
  spring.datasource.password: testpassword
  jwt.secret: MjgwNGRkMDYzMGQ1MzAyZjAwMzYyYjE1
  spring.mail.username: khajbdran@gmail.com
  spring.mail.password: gorvrxjkdwxgyoxf
