apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: os-data
  namespace: takatuf   # غيريها إذا عندك ns تانية
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 500Mi   # مساحة صغيرة كفاية للتجربة
